class Division {
  String name;
  List<District> districts;

  Division({required this.name, required this.districts});
  @override
  String toString() {
    return name;
  }
}

class District {
  String name;
  List<SubDistrict> subDistricts;

  District({required this.name, required this.subDistricts});
  @override
  String toString() {
    return name;
  }
}

class SubDistrict {
  String name;

  SubDistrict({required this.name});
  @override
  String toString() {
    return name;
  }
}

List<Division> get getDivisions {
  return [
    Division(name: 'Barisal', districts: [
      District(name: 'Barguna', subDistricts: [
        SubDistrict(name: 'Amtali'),
        SubDistrict(name: 'Bamna'),
        SubDistrict(name: 'Barguna Sadar'),
        SubDistrict(name: 'Betagi'),
        SubDistrict(name: 'Patharghata'),
        SubDistrict(name: 'Taltali'),
      ]),
      District(name: 'Barisal', subDistricts: [
        SubDistrict(name: 'Agailjhara'),
        SubDistrict(name: 'Babuganj'),
        SubDistrict(name: 'Bakerganj'),
        SubDistrict(name: 'Banaripara'),
        SubDistrict(name: 'Gaurnadi'),
        SubDistrict(name: 'Hizla'),
        SubDistrict(name: 'Barishal Sadar'),
        SubDistrict(name: 'Mehendiganj'),
        SubDistrict(name: 'Muladi'),
        SubDistrict(name: 'Wazirpur'),
      ]),
      District(name: 'Bhola', subDistricts: [
        SubDistrict(name: 'Bhola Sadar'),
        SubDistrict(name: 'Burhanuddin'),
        SubDistrict(name: 'Char Fasson'),
        SubDistrict(name: 'Daulatkhan'),
        SubDistrict(name: 'Lalmohan'),
        SubDistrict(name: 'Manpura'),
        SubDistrict(name: 'Tazumuddin'),
      ]),
      District(name: 'Jhalokati', subDistricts: [
        SubDistrict(name: 'Jhalokati Sadar'),
        SubDistrict(name: 'Kathalia'),
        SubDistrict(name: 'Nalchity'),
        SubDistrict(name: 'Rajapur'),
      ]),
      District(name: 'Patuakhali', subDistricts: [
        SubDistrict(name: 'Bauphal'),
        SubDistrict(name: 'Dashmina'),
        SubDistrict(name: 'Galachipa'),
        SubDistrict(name: 'Kalapara'),
        SubDistrict(name: 'Mirzaganj'),
        SubDistrict(name: 'Patuakhali Sadar'),
        SubDistrict(name: 'Rangabali'),
        SubDistrict(name: 'Dumki'),
      ]),
      District(name: 'Pirojpur', subDistricts: [
        SubDistrict(name: 'Bhandaria'),
        SubDistrict(name: 'Kawkhali'),
        SubDistrict(name: 'Mathbaria'),
        SubDistrict(name: 'Nazirpur'),
        SubDistrict(name: 'Pirojpur Sadar'),
        SubDistrict(name: 'Nesarabad (Swarupkati)'),
        SubDistrict(name: 'Zianagar'),
      ]),
    ]),
    Division(name: 'Chittagong', districts: [
      District(name: 'Bandarban', subDistricts: [
        SubDistrict(name: 'Ali Kadam'),
        SubDistrict(name: 'Bandarban Sadar'),
        SubDistrict(name: 'Lama'),
        SubDistrict(name: 'Naikhongchhari'),
        SubDistrict(name: 'Rowangchhari'),
        SubDistrict(name: 'Ruma'),
        SubDistrict(name: 'Thanchi'),
      ]),
      District(name: 'Brahmanbaria', subDistricts: [
        SubDistrict(name: 'Akhaura'),
        SubDistrict(name: 'Bancharampur'),
        SubDistrict(name: 'Brahmanbaria Sadar'),
        SubDistrict(name: 'Kasba'),
        SubDistrict(name: 'Nabinagar'),
        SubDistrict(name: 'Nasirnagar'),
        SubDistrict(name: 'Sarail'),
        SubDistrict(name: 'Ashuganj'),
        SubDistrict(name: 'Bijoynagar'),
      ]),
      District(name: 'Chandpur', subDistricts: [
        SubDistrict(name: 'Chandpur Sadar'),
        SubDistrict(name: 'Faridganj'),
        SubDistrict(name: 'Haimchar'),
        SubDistrict(name: 'Haziganj'),
        SubDistrict(name: 'Kachua'),
        SubDistrict(name: 'Matlab Dakshin'),
        SubDistrict(name: 'Matlab Uttar'),
        SubDistrict(name: 'Shahrasti'),
      ]),
      District(name: 'Chittagong', subDistricts: [
        SubDistrict(name: 'Anwara'),
        SubDistrict(name: 'Banshkhali'),
        SubDistrict(name: 'Boalkhali'),
        SubDistrict(name: 'Chandanaish'),
        SubDistrict(name: 'Fatikchhari'),
        SubDistrict(name: 'Hathazari'),
        SubDistrict(name: 'Karnaphuli'),
        SubDistrict(name: 'Lohagara'),
        SubDistrict(name: 'Mirsharai'),
        SubDistrict(name: 'Patiya'),
        SubDistrict(name: 'Rangunia'),
        SubDistrict(name: 'Raozan'),
        SubDistrict(name: 'Sandwip'),
        SubDistrict(name: 'Satkania'),
        SubDistrict(name: 'Sitakunda'),
        SubDistrict(name: 'Bandar Thana'),
        SubDistrict(name: 'Chandgaon Thana'),
        SubDistrict(name: 'Double Mooring Thana'),
        SubDistrict(name: 'Kotwali Thana'),
        SubDistrict(name: 'Pahartali Thana'),
        SubDistrict(name: 'Panchlaish Thana'),
        SubDistrict(name: 'Bhujpur Thana'),
      ]),
      District(name: 'Comilla', subDistricts: [
        SubDistrict(name: 'Barura'),
        SubDistrict(name: 'Brahmanpara'),
        SubDistrict(name: 'Burichang'),
        SubDistrict(name: 'Chandina'),
        SubDistrict(name: 'Chauddagram'),
        SubDistrict(name: 'Daudkandi'),
        SubDistrict(name: 'Debidwar'),
        SubDistrict(name: 'Homna'),
        SubDistrict(name: 'Laksam'),
        SubDistrict(name: 'Muradnagar'),
        SubDistrict(name: 'Nangalkot'),
        SubDistrict(name: 'Cumilla Adarsha Sadar'),
        SubDistrict(name: 'Meghna'),
        SubDistrict(name: 'Titas'),
        SubDistrict(name: 'Monohargonj'),
        SubDistrict(name: 'Cumilla Sadar Dakshin'),
      ]),
      District(name: 'Cox\'s Bazar', subDistricts: [
        SubDistrict(name: 'Chakaria'),
        SubDistrict(name: 'Cox\'s Bazar Sadar'),
        SubDistrict(name: 'Kutubdia'),
        SubDistrict(name: 'Maheshkhali'),
        SubDistrict(name: 'Ramu'),
        SubDistrict(name: 'Teknaf'),
        SubDistrict(name: 'Ukhia'),
        SubDistrict(name: 'Pekua'),
      ]),
      District(name: 'Feni', subDistricts: [
        SubDistrict(name: 'Chhagalnaiya'),
        SubDistrict(name: 'Daganbhuiyan'),
        SubDistrict(name: 'Feni Sadar'),
        SubDistrict(name: 'Parshuram'),
        SubDistrict(name: 'Sonagazi'),
        SubDistrict(name: 'Fulgazi'),
      ]),
      District(name: 'Khagrachhari', subDistricts: [
        SubDistrict(name: 'Dighinala'),
        SubDistrict(name: 'Khagrachhari'),
        SubDistrict(name: 'Lakshmichhari'),
        SubDistrict(name: 'Mahalchhari'),
        SubDistrict(name: 'Manikchhari'),
        SubDistrict(name: 'Matiranga'),
        SubDistrict(name: 'Panchhari'),
        SubDistrict(name: 'Ramgarh'),
      ]),
      District(name: 'Lakshmipur', subDistricts: [
        SubDistrict(name: 'Lakshmipur Sadar'),
        SubDistrict(name: 'Raipur'),
        SubDistrict(name: 'Ramganj'),
        SubDistrict(name: 'Ramgati'),
        SubDistrict(name: 'Kamalnagar'),
      ]),
      District(name: 'Noakhali', subDistricts: [
        SubDistrict(name: 'Begumganj'),
        SubDistrict(name: 'Noakhali Sadar'),
        SubDistrict(name: 'Chatkhil'),
        SubDistrict(name: 'Companiganj'),
        SubDistrict(name: 'Hatiya'),
        SubDistrict(name: 'Senbagh'),
        SubDistrict(name: 'Sonaimuri'),
        SubDistrict(name: 'Subarnachar'),
        SubDistrict(name: 'Kabirhat'),
      ]),
      District(name: 'Rangamati', subDistricts: [
        SubDistrict(name: 'Bagaichhari'),
        SubDistrict(name: 'Barkal'),
        SubDistrict(name: 'Kawkhali (Betbunia)'),
        SubDistrict(name: 'Belaichhari'),
        SubDistrict(name: 'Kaptai'),
        SubDistrict(name: 'Juraichhari'),
        SubDistrict(name: 'Langadu'),
        SubDistrict(name: 'Naniyachar'),
        SubDistrict(name: 'Rajasthali'),
        SubDistrict(name: 'Rangamati Sadar'),
      ]),
    ]),
    Division(name: 'Dhaka', districts: [
      District(name: 'Dhaka', subDistricts: [
        SubDistrict(name: 'Dhamrai'),
        SubDistrict(name: 'Dohar'),
        SubDistrict(name: 'Keraniganj'),
        SubDistrict(name: 'Nawabganj'),
        SubDistrict(name: 'Savar'),
        SubDistrict(name: 'Tejgaon Circle'),
      ]),
      District(name: 'Faridpur', subDistricts: [
        SubDistrict(name: 'Alfadanga'),
        SubDistrict(name: 'Bhanga'),
        SubDistrict(name: 'Boalmari'),
        SubDistrict(name: 'Charbhadrasan'),
        SubDistrict(name: 'Faridpur Sadar'),
        SubDistrict(name: 'Madhukhali'),
        SubDistrict(name: 'Nagarkanda'),
        SubDistrict(name: 'Sadarpur'),
        SubDistrict(name: 'Saltha'),
      ]),
      District(name: 'Gazipur', subDistricts: [
        SubDistrict(name: 'Gazipur Sadar'),
        SubDistrict(name: 'Kaliakair'),
        SubDistrict(name: 'Kaliganj'),
        SubDistrict(name: 'Kapasia'),
        SubDistrict(name: 'Sreepur'),
      ]),
      District(name: 'Gopalganj', subDistricts: [
        SubDistrict(name: 'Gopalganj Sadar'),
        SubDistrict(name: 'Kashiani'),
        SubDistrict(name: 'Kotalipara'),
        SubDistrict(name: 'Muksudpur'),
        SubDistrict(name: 'Tungipara'),
      ]),
      District(name: 'Kishoreganj', subDistricts: [
        SubDistrict(name: 'Austagram'),
        SubDistrict(name: 'Bajitpur'),
        SubDistrict(name: 'Bhairab'),
        SubDistrict(name: 'Hossainpur'),
        SubDistrict(name: 'Itna'),
        SubDistrict(name: 'Karimganj'),
        SubDistrict(name: 'Katiadi'),
        SubDistrict(name: 'Kishoreganj Sadar'),
        SubDistrict(name: 'Kuliarchar'),
        SubDistrict(name: 'Mithamain'),
        SubDistrict(name: 'Nikli'),
        SubDistrict(name: 'Pakundia'),
      ]),
      District(name: 'Madaripur', subDistricts: [
        SubDistrict(name: 'Rajoir'),
        SubDistrict(name: 'Madaripur Sadar'),
        SubDistrict(name: 'Kalkini'),
        SubDistrict(name: 'Shibchar'),
      ]),
      District(name: 'Manikganj', subDistricts: [
        SubDistrict(name: 'Daulatpur'),
        SubDistrict(name: 'Ghior'),
        SubDistrict(name: 'Harirampur'),
        SubDistrict(name: 'Manikgonj Sadar'),
        SubDistrict(name: 'Saturia'),
        SubDistrict(name: 'Shivalaya'),
        SubDistrict(name: 'Singair'),
      ]),
      District(name: 'Munshiganj', subDistricts: [
        SubDistrict(name: 'Gazaria'),
        SubDistrict(name: 'Lohajang'),
        SubDistrict(name: 'Munshiganj Sadar'),
        SubDistrict(name: 'Sirajdikhan'),
        SubDistrict(name: 'Sreenagar'),
        SubDistrict(name: 'Tongibari'),
      ]),
      District(name: 'Narayanganj', subDistricts: [
        SubDistrict(name: 'Araihazar'),
        SubDistrict(name: 'Bandar'),
        SubDistrict(name: 'Narayanganj Sadar'),
        SubDistrict(name: 'Rupganj'),
        SubDistrict(name: 'Sonargaon'),
      ]),
      District(name: 'Narsingdi', subDistricts: [
        SubDistrict(name: 'Narsingdi Sadar'),
        SubDistrict(name: 'Belabo'),
        SubDistrict(name: 'Monohardi'),
        SubDistrict(name: 'Palash'),
        SubDistrict(name: 'Raipura'),
        SubDistrict(name: 'Shibpur'),
      ]),
      District(name: 'Rajbari', subDistricts: [
        SubDistrict(name: 'Baliakandi'),
        SubDistrict(name: 'Goalandaghat'),
        SubDistrict(name: 'Pangsha'),
        SubDistrict(name: 'Rajbari Sadar'),
        SubDistrict(name: 'Kalukhali'),
      ]),
      District(name: 'Shariatpur', subDistricts: [
        SubDistrict(name: 'Bhedarganj'),
        SubDistrict(name: 'Damudya'),
        SubDistrict(name: 'Gosairhat'),
        SubDistrict(name: 'Naria'),
        SubDistrict(name: 'Shariatpur Sadar'),
        SubDistrict(name: 'Zajira'),
        SubDistrict(name: 'Shakhipur'),
      ]),
      District(name: 'Tangail', subDistricts: [
        SubDistrict(name: 'Gopalpur'),
        SubDistrict(name: 'Basail'),
        SubDistrict(name: 'Bhuapur'),
        SubDistrict(name: 'Delduar'),
        SubDistrict(name: 'Ghatail'),
        SubDistrict(name: 'Kalihati'),
        SubDistrict(name: 'Madhupur'),
        SubDistrict(name: 'Mirzapur'),
        SubDistrict(name: 'Nagarpur'),
        SubDistrict(name: 'Sakhipur'),
        SubDistrict(name: 'Dhanbari'),
        SubDistrict(name: 'Tangail Sadar'),
      ]),
    ]),
    Division(name: 'Khulna', districts: [
      District(name: 'Bagerhat', subDistricts: [
        SubDistrict(name: 'Bagerhat Sadar'),
        SubDistrict(name: 'Chitalmari'),
        SubDistrict(name: 'Fakirhat'),
        SubDistrict(name: 'Kachua'),
        SubDistrict(name: 'Mollahat'),
        SubDistrict(name: 'Mongla'),
        SubDistrict(name: 'Morrelganj'),
        SubDistrict(name: 'Rampal'),
        SubDistrict(name: 'Sarankhola'),
      ]),
      District(name: 'Chuadanga', subDistricts: [
        SubDistrict(name: 'Alamdanga'),
        SubDistrict(name: 'Chuadanga Sadar'),
        SubDistrict(name: 'Damurhuda'),
        SubDistrict(name: 'Jibannagar'),
      ]),
      District(name: 'Jessore', subDistricts: [
        SubDistrict(name: 'Abhaynagar'),
        SubDistrict(name: 'Bagherpara'),
        SubDistrict(name: 'Chaugachha'),
        SubDistrict(name: 'Jhikargachha'),
        SubDistrict(name: 'Keshabpur'),
        SubDistrict(name: 'Jashore Sadar'),
        SubDistrict(name: 'Manirampur'),
        SubDistrict(name: 'Sharsha'),
      ]),
      District(name: 'Jhenaidah', subDistricts: [
        SubDistrict(name: 'Harinakunda'),
        SubDistrict(name: 'Jhenaidah Sadar'),
        SubDistrict(name: 'Kaliganj'),
        SubDistrict(name: 'Kotchandpur'),
        SubDistrict(name: 'Maheshpur'),
        SubDistrict(name: 'Shailkupa'),
      ]),
      District(name: 'Khulna', subDistricts: [
        SubDistrict(name: 'Batiaghata'),
        SubDistrict(name: 'Dacope'),
        SubDistrict(name: 'Dumuria'),
        SubDistrict(name: 'Dighalia'),
        SubDistrict(name: 'Koyra'),
        SubDistrict(name: 'Paikgachha'),
        SubDistrict(name: 'Phultala'),
        SubDistrict(name: 'Rupsha'),
        SubDistrict(name: 'Terokhada'),
        SubDistrict(name: 'Daulatpur Thana'),
        SubDistrict(name: 'Khalishpur Thana'),
        SubDistrict(name: 'Khan Jahan Ali Thana'),
        SubDistrict(name: 'Kotwali Thana'),
        SubDistrict(name: 'Sonadanga Thana'),
        SubDistrict(name: 'Harintana Thana'),
      ]),
      District(name: 'Kushtia', subDistricts: [
        SubDistrict(name: 'Bheramara'),
        SubDistrict(name: 'Daulatpur'),
        SubDistrict(name: 'Khoksa'),
        SubDistrict(name: 'Kumarkhali'),
        SubDistrict(name: 'Kushtia Sadar'),
        SubDistrict(name: 'Mirpur'),
      ]),
      District(name: 'Magura', subDistricts: [
        SubDistrict(name: 'Magura Sadar'),
        SubDistrict(name: 'Mohammadpur'),
        SubDistrict(name: 'Shalikha'),
        SubDistrict(name: 'Sreepur'),
      ]),
      District(name: 'Meherpur', subDistricts: [
        SubDistrict(name: 'Gangni'),
        SubDistrict(name: 'Meherpur Sadar'),
        SubDistrict(name: 'Mujibnagar'),
      ]),
      District(name: 'Narail', subDistricts: [
        SubDistrict(name: 'Kalia'),
        SubDistrict(name: 'Lohagara'),
        SubDistrict(name: 'Narail Sadar'),
        SubDistrict(name: 'Naragati Thana'),
      ]),
      District(name: 'Satkhira', subDistricts: [
        SubDistrict(name: 'Assasuni'),
        SubDistrict(name: 'Debhata'),
        SubDistrict(name: 'Kalaroa'),
        SubDistrict(name: 'Kaliganj'),
        SubDistrict(name: 'Satkhira Sadar'),
        SubDistrict(name: 'Shyamnagar'),
        SubDistrict(name: 'Tala'),
      ]),
    ]),
    Division(name: 'Mymensingh', districts: [
      District(name: 'Jamalpur', subDistricts: [
        SubDistrict(name: 'Baksiganj'),
        SubDistrict(name: 'Dewanganj'),
        SubDistrict(name: 'Islampur'),
        SubDistrict(name: 'Jamalpur Sadar'),
        SubDistrict(name: 'Madarganj'),
        SubDistrict(name: 'Melandaha'),
        SubDistrict(name: 'Sarishabari'),
      ]),
      District(name: 'Mymensingh', subDistricts: [
        SubDistrict(name: 'Trishal'),
        SubDistrict(name: 'Dhobaura'),
        SubDistrict(name: 'Fulbaria'),
        SubDistrict(name: 'Gaffargaon'),
        SubDistrict(name: 'Gauripur'),
        SubDistrict(name: 'Haluaghat'),
        SubDistrict(name: 'Ishwarganj'),
        SubDistrict(name: 'Mymensingh Sadar'),
        SubDistrict(name: 'Muktagachha'),
        SubDistrict(name: 'Nandail'),
        SubDistrict(name: 'Phulpur'),
        SubDistrict(name: 'Bhaluka'),
        SubDistrict(name: 'Tara Khanda'),
      ]),
      District(name: 'Netrakona', subDistricts: [
        SubDistrict(name: 'Atpara'),
        SubDistrict(name: 'Barhatta'),
        SubDistrict(name: 'Durgapur'),
        SubDistrict(name: 'Khaliajuri'),
        SubDistrict(name: 'Kalmakanda'),
        SubDistrict(name: 'Kendua'),
        SubDistrict(name: 'Madan'),
        SubDistrict(name: 'Mohanganj'),
        SubDistrict(name: 'Netrokona Sadar'),
        SubDistrict(name: 'Purbadhala'),
      ]),
      District(name: 'Sherpur', subDistricts: [
        SubDistrict(name: 'Jhenaigati'),
        SubDistrict(name: 'Nakla'),
        SubDistrict(name: 'Nalitabari'),
        SubDistrict(name: 'Sherpur Sadar'),
        SubDistrict(name: 'Sreebardi'),
      ]),
    ]),
    Division(name: 'Rajshahi', districts: [
      District(name: 'Bogra', subDistricts: [
        SubDistrict(name: 'Adamdighi'),
        SubDistrict(name: 'Bogura Sadar'),
        SubDistrict(name: 'Dhunat'),
        SubDistrict(name: 'Dhupchanchia'),
        SubDistrict(name: 'Gabtali'),
        SubDistrict(name: 'Kahaloo'),
        SubDistrict(name: 'Nandigram'),
        SubDistrict(name: 'Sariakandi'),
        SubDistrict(name: 'Shajahanpur'),
        SubDistrict(name: 'Sherpur'),
        SubDistrict(name: 'Shibganj'),
        SubDistrict(name: 'Sonatola'),
      ]),
      District(name: 'Chapainawabganj', subDistricts: [
        SubDistrict(name: 'Bholahat'),
        SubDistrict(name: 'Gomastapur'),
        SubDistrict(name: 'Nachole'),
        SubDistrict(name: 'Nawabganj Sadar'),
        SubDistrict(name: 'Shibganj'),
      ]),
      District(name: 'Joypurhat', subDistricts: [
        SubDistrict(name: 'Akkelpur'),
        SubDistrict(name: 'Joypurhat Sadar'),
        SubDistrict(name: 'Kalai'),
        SubDistrict(name: 'Khetlal'),
        SubDistrict(name: 'Panchbibi'),
      ]),
      District(name: 'Naogaon', subDistricts: [
        SubDistrict(name: 'Atrai'),
        SubDistrict(name: 'Badalgachhi'),
        SubDistrict(name: 'Manda'),
        SubDistrict(name: 'Dhamoirhat'),
        SubDistrict(name: 'Mohadevpur'),
        SubDistrict(name: 'Naogaon Sadar'),
        SubDistrict(name: 'Niamatpur'),
        SubDistrict(name: 'Patnitala'),
        SubDistrict(name: 'Porsha'),
        SubDistrict(name: 'Raninagar'),
        SubDistrict(name: 'Sapahar'),
      ]),
      District(name: 'Natore', subDistricts: [
        SubDistrict(name: 'Bagatipara'),
        SubDistrict(name: 'Baraigram'),
        SubDistrict(name: 'Gurudaspur'),
        SubDistrict(name: 'Lalpur'),
        SubDistrict(name: 'Natore Sadar'),
        SubDistrict(name: 'Singra'),
        SubDistrict(name: 'Naldanga'),
      ]),
      District(name: 'Pabna', subDistricts: [
        SubDistrict(name: 'Atgharia'),
        SubDistrict(name: 'Bera'),
        SubDistrict(name: 'Bhangura'),
        SubDistrict(name: 'Chatmohar'),
        SubDistrict(name: 'Faridpur'),
        SubDistrict(name: 'Ishwardi'),
        SubDistrict(name: 'Pabna Sadar'),
        SubDistrict(name: 'Santhia'),
        SubDistrict(name: 'Sujanagar'),
      ]),
      District(name: 'Rajshahi', subDistricts: [
        SubDistrict(name: 'Bagha'),
        SubDistrict(name: 'Bagmara'),
        SubDistrict(name: 'Charghat'),
        SubDistrict(name: 'Durgapur'),
        SubDistrict(name: 'Godagari'),
        SubDistrict(name: 'Mohanpur'),
        SubDistrict(name: 'Paba'),
        SubDistrict(name: 'Puthia'),
        SubDistrict(name: 'Tanore'),
      ]),
      District(name: 'Sirajganj', subDistricts: [
        SubDistrict(name: 'Belkuchi'),
        SubDistrict(name: 'Chauhali'),
        SubDistrict(name: 'Kamarkhanda'),
        SubDistrict(name: 'Kazipur'),
        SubDistrict(name: 'Raiganj'),
        SubDistrict(name: 'Shahjadpur'),
        SubDistrict(name: 'Sirajganj Sadar'),
        SubDistrict(name: 'Tarash'),
        SubDistrict(name: 'Ullahpara'),
      ]),
    ]),
    Division(name: 'Rangpur', districts: [
      District(name: 'Dinajpur', subDistricts: [
        SubDistrict(name: 'Birampur'),
        SubDistrict(name: 'Birganj'),
        SubDistrict(name: 'Biral'),
        SubDistrict(name: 'Bochaganj'),
        SubDistrict(name: 'Chirirbandar'),
        SubDistrict(name: 'Phulbari'),
        SubDistrict(name: 'Ghoraghat'),
        SubDistrict(name: 'Hakimpur'),
        SubDistrict(name: 'Kaharole'),
        SubDistrict(name: 'Khansama'),
        SubDistrict(name: 'Dinajpur Sadar'),
        SubDistrict(name: 'Nawabganj'),
        SubDistrict(name: 'Parbatipur'),
      ]),
      District(name: 'Gaibandha', subDistricts: [
        SubDistrict(name: 'Phulchhari'),
        SubDistrict(name: 'Gaibandha Sadar'),
        SubDistrict(name: 'Gobindaganj'),
        SubDistrict(name: 'Palashbari'),
        SubDistrict(name: 'Sadullapur'),
        SubDistrict(name: 'Sughatta'),
        SubDistrict(name: 'Sundarganj'),
      ]),
      District(name: 'Kurigram', subDistricts: [
        SubDistrict(name: 'Bhurungamari'),
        SubDistrict(name: 'Char Rajibpur'),
        SubDistrict(name: 'Chilmari'),
        SubDistrict(name: 'Phulbari'),
        SubDistrict(name: 'Kurigram Sadar'),
        SubDistrict(name: 'Nageshwari'),
        SubDistrict(name: 'Rajarhat'),
        SubDistrict(name: 'Raomari'),
        SubDistrict(name: 'Ulipur'),
      ]),
      District(name: 'Lalmonirhat', subDistricts: [
        SubDistrict(name: 'Aditmari'),
        SubDistrict(name: 'Hatibandha'),
        SubDistrict(name: 'Kaliganj'),
        SubDistrict(name: 'Lalmonirhat Sadar'),
        SubDistrict(name: 'Patgram'),
      ]),
      District(name: 'Nilphamari', subDistricts: [
        SubDistrict(name: 'Dimla'),
        SubDistrict(name: 'Domar'),
        SubDistrict(name: 'Jaldhaka'),
        SubDistrict(name: 'Kishoreganj'),
        SubDistrict(name: 'Nilphamari Sadar'),
        SubDistrict(name: 'Saidpur'),
      ]),
      District(name: 'Panchagarh', subDistricts: [
        SubDistrict(name: 'Atwari'),
        SubDistrict(name: 'Boda'),
        SubDistrict(name: 'Debiganj'),
        SubDistrict(name: 'Panchagarh Sadar'),
        SubDistrict(name: 'Tetulia'),
      ]),
      District(name: 'Rangpur', subDistricts: [
        SubDistrict(name: 'Badarganj'),
        SubDistrict(name: 'Gangachhara'),
        SubDistrict(name: 'Kaunia'),
        SubDistrict(name: 'Rangpur Sadar'),
        SubDistrict(name: 'Mithapukur'),
        SubDistrict(name: 'Pirgachha'),
        SubDistrict(name: 'Pirganj'),
        SubDistrict(name: 'Taraganj'),
      ]),
      District(name: 'Thakurgaon', subDistricts: [
        SubDistrict(name: 'Baliadangi'),
        SubDistrict(name: 'Haripur'),
        SubDistrict(name: 'Pirganj'),
        SubDistrict(name: 'Ranisankail'),
        SubDistrict(name: 'Thakurgaon Sadar'),
      ]),
    ]),
    Division(name: 'Sylhet', districts: [
      District(name: 'Habiganj', subDistricts: [
        SubDistrict(name: 'Ajmiriganj'),
        SubDistrict(name: 'Bahubal'),
        SubDistrict(name: 'Baniyachong'),
        SubDistrict(name: 'Chunarughat'),
        SubDistrict(name: 'Habiganj Sadar'),
        SubDistrict(name: 'Lakhai'),
        SubDistrict(name: 'Madhabpur'),
        SubDistrict(name: 'Nabiganj'),
        SubDistrict(name: 'Sayestaganj'),
      ]),
      District(name: 'Moulvibazar', subDistricts: [
        SubDistrict(name: 'Barlekha'),
        SubDistrict(name: 'Juri'),
        SubDistrict(name: 'Kamalganj'),
        SubDistrict(name: 'Kulaura'),
        SubDistrict(name: 'Moulvibazar Sadar'),
        SubDistrict(name: 'Rajnagar'),
        SubDistrict(name: 'Sreemangal'),
      ]),
      District(name: 'Sunamganj', subDistricts: [
        SubDistrict(name: 'Bishwamvarpur'),
        SubDistrict(name: 'Chhatak'),
        SubDistrict(name: 'Dakshin Sunamganj'),
        SubDistrict(name: 'Derai'),
        SubDistrict(name: 'Dharamapasha'),
        SubDistrict(name: 'Dowarabazar'),
        SubDistrict(name: 'Jagannathpur'),
        SubDistrict(name: 'Jamalganj'),
        SubDistrict(name: 'Sullah'),
        SubDistrict(name: 'Sunamganj Sadar'),
        SubDistrict(name: 'Tahirpur'),
      ]),
      District(name: 'Sylhet', subDistricts: [
        SubDistrict(name: 'Balaganj'),
        SubDistrict(name: 'Beanibazar'),
        SubDistrict(name: 'Bishwanath'),
        SubDistrict(name: 'Companigonj'),
        SubDistrict(name: 'Dakshin Surma'),
        SubDistrict(name: 'Fenchuganj'),
        SubDistrict(name: 'Golapganj'),
        SubDistrict(name: 'Gowainghat'),
        SubDistrict(name: 'Jaintiapur'),
        SubDistrict(name: 'Kanaighat'),
        SubDistrict(name: 'Osmani Nagar'),
        SubDistrict(name: 'Sylhet Sadar'),
        SubDistrict(name: 'Zakiganj'),
      ]),
    ]),
  ];
}